# Generated by Django 3.1.7 on 2021-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0004_posteos_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='texto',
            field=models.TextField(max_length=100),
        ),
    ]
