# Generated by Django 3.1.7 on 2021-04-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0005_auto_20210407_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='texto',
            field=models.TextField(max_length=300),
        ),
    ]
