# Generated by Django 3.1.7 on 2021-04-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0006_auto_20210407_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteos',
            options={'ordering': ['fecha_pub']},
        ),
    ]
