# Generated by Django 3.1.7 on 2021-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0007_auto_20210407_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteos',
            options={'ordering': ['-fecha_pub']},
        ),
        migrations.AlterField(
            model_name='posteos',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
