# Generated by Django 3.1.7 on 2021-04-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0008_auto_20210407_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='archivo',
            field=models.FileField(default='', upload_to='postarchivos/'),
        ),
    ]
