# Generated by Django 3.1.7 on 2021-04-07 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0009_posteos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='fecha_pub',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
