# Generated by Django 3.1.7 on 2021-04-08 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0011_auto_20210407_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='fecha_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
