# Generated by Django 3.2.4 on 2021-08-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0013_auto_20210408_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgrados',
            name='estado',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Finished', 'Finished')], default='In Progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='tgrados',
            name='modalidad',
            field=models.CharField(choices=[('Diploma Course', 'Diploma Course'), ('Research Case', 'Research Case'), ('Entrepeneuership work', 'Entrepeneuership work')], default='Study Case Research', max_length=100),
        ),
    ]
