# Generated by Django 3.2.4 on 2021-08-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusc', '0014_auto_20210821_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgrados',
            old_name='estado',
            new_name='Status',
        ),
    ]
